import { ArrowBackIosNew } from "@mui/icons-material";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";

function TermsOfService() {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);
  const navigate = useNavigate();

  return (
    <div className="min-h-screen overflow-hidden bg-gradient-to-br from-slate-950 via-[#141A4B] to-slate-900 py-16 px-2 flex items-center justify-center">
      <div className="w-full max-w-3xl mx-auto rounded-2xl bg-[#181A3B]/80 backdrop-blur-md shadow-xl border border-purple-500/10 p-6 sm:p-12 relative">
        {/* Decorative Gradient Orb */}
        <div className="absolute -top-16 -left-16 w-48 h-48 bg-purple-500/20 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -bottom-16 -right-16 w-72 h-72 bg-pink-500/15 rounded-full blur-3xl pointer-events-none" />
        <button
          onClick={() => navigate(-1)}
          className="flex absolute items-center gap-2 px-3 sm:px-5 py-2  rounded-full bg-gradient-to-r from-purple-500 to-pink-500 text-white font-medium shadow hover:scale-102 hover:shadow-lg transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-purple-400 cursor-pointer"
        >
          <ArrowBackIosNew fontSize="small" />
          <span className="hidden sm:block">Go Back</span>
        </button>
        <h1 className="text-3xl sm:text-4xl font-bold text-center mb-4 bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
          Terms of Service
        </h1>
        <p className="text-center text-gray-400 mb-8 text-sm">
          Effective Date: <span className="font-medium">[Insert Date]</span>
        </p>
        <div className="prose prose-invert max-w-none text-gray-300">
          <h2 className="mt-0 text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            1. Description of Service
          </h2>
          <p>
            Senti Mind enables users to generate AI-powered articles from social
            media inputs (hashtags, handles, queries) using Google’s Gemini API.
            We offer tiered subscription plans: Free, Basic, Pro, and Ultra.
          </p>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            2. User Accounts
          </h2>
          <ul>
            <li>You must provide accurate information when signing up.</li>
            <li>You are responsible for all activity on your account.</li>
            <li>You may delete your account at any time.</li>
          </ul>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            3. Subscription & Payments
          </h2>
          <ul>
            <li>Subscriptions are processed via Razorpay.</li>
            <li>Plans: Free, Basic, Pro, Ultra.</li>
            <li>
              You may cancel your subscription anytime; access continues until
              the end of your billing cycle.
            </li>
            <li>No refunds unless required by law.</li>
          </ul>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            4. Generated Content
          </h2>
          <ul>
            <li>Content is generated by AI and may contain inaccuracies.</li>
            <li>You are responsible for how you use or share the content.</li>
            <li>We do not guarantee factual accuracy.</li>
          </ul>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            5. Intellectual Property
          </h2>
          <ul>
            <li>
              Generated content may be used for personal or commercial purposes
              (as per your plan).
            </li>
            <li>
              Senti Mind retains all rights to the service platform and
              branding.
            </li>
          </ul>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            6. Prohibited Use
          </h2>
          <ul>
            <li>Abuse the service or automate scraping of input/output</li>
            <li>Use the platform for illegal or harmful content generation</li>
            <li>Attempt to reverse engineer or disrupt the service</li>
          </ul>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            7. Limitation of Liability
          </h2>
          <p>
            Senti Mind is not liable for indirect damages, data loss, or errors
            in generated content. Use is at your own risk.
          </p>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            8. Termination
          </h2>
          <p>
            We may suspend or terminate accounts violating these terms without
            prior notice.
          </p>
          <h2 className="text-xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 text-transparent bg-clip-text">
            9. Governing Law
          </h2>
          <p>
            These Terms are governed by the laws of India. Any disputes will be
            subject to the jurisdiction of [Your City/State Court].
          </p>
        </div>
      </div>
    </div>
  );
}

export default TermsOfService;
